const EXERCISE_DB = [
  { category: "Chest", name: "Bench press" },
  { category: "Chest", name: "Bench press (dumbbell)" },
  { category: "Chest", name: "Incline bench press" },
  { category: "Chest", name: "Incline bench press (dumbbell)" },
  { category: "Chest", name: "Decline bench press" },
  { category: "Chest", name: "Flyes (machine)" },
  { category: "Chest", name: "Flyes (cable)" },
  { category: "Chest", name: "Flyes (dumbbell)" },
  { category: "Chest", name: "Push-ups" },
  { category: "Chest", name: "Dips (chest)" },
  { category: "Chest", name: "Cable crossover" },
  { category: "Chest", name: "Pullover (dumbbell)" },

  { category: "Back", name: "Deadlift" },
  { category: "Back", name: "Sumo deadlift" },
  { category: "Back", name: "Romanian deadlift" },
  { category: "Back", name: "Lat pulldown" },
  { category: "Back", name: "Seated cable row" },
  { category: "Back", name: "Bent-over barbell row" },
  { category: "Back", name: "Bent-over dumbbell row" },
  { category: "Back", name: "T-bar row" },
  { category: "Back", name: "Chin-ups" },
  { category: "Back", name: "Pull-ups" },
  { category: "Back", name: "One-arm dumbbell row" },
  { category: "Back", name: "Machine row" },
  { category: "Back", name: "Face pulls" },
  { category: "Back", name: "Shrugs (barbell)" },
  { category: "Back", name: "Shrugs (dumbbell)" },
  { category: "Back", name: "Hyperextensions" },
  { category: "Back", name: "Good mornings" },

  { category: "Shoulders", name: "Military press (barbell)" },
  { category: "Shoulders", name: "Shoulder press (dumbbell)" },
  { category: "Shoulders", name: "Arnold press" },
  { category: "Shoulders", name: "Lateral raises (dumbbell)" },
  { category: "Shoulders", name: "Lateral raises (cable)" },
  { category: "Shoulders", name: "Front raises (dumbbell)" },
  { category: "Shoulders", name: "Front raises (cable)" },
  { category: "Shoulders", name: "Rear delt flyes (dumbbell)" },
  { category: "Shoulders", name: "Rear delt flyes (machine)" },
  { category: "Shoulders", name: "Upright row (barbell)" },
  { category: "Shoulders", name: "Upright row (cable)" },
  { category: "Shoulders", name: "Machine shoulder press" },

  { category: "Biceps", name: "Barbell curl" },
  { category: "Biceps", name: "Dumbbell curl" },
  { category: "Biceps", name: "Hammer curl" },
  { category: "Biceps", name: "Concentration curl" },
  { category: "Biceps", name: "Preacher curl (barbell)" },
  { category: "Biceps", name: "Preacher curl (dumbbell)" },
  { category: "Biceps", name: "Cable curl" },
  { category: "Biceps", name: "Incline dumbbell curl" },
  { category: "Biceps", name: "Spider curl" },
  { category: "Biceps", name: "Reverse curl" },
  { category: "Biceps", name: "Chin-ups (biceps)" },

  { category: "Triceps", name: "Triceps pushdown (cable)" },
  { category: "Triceps", name: "Skull crushers (barbell)" },
  { category: "Triceps", name: "Skull crushers (dumbbell)" },
  { category: "Triceps", name: "Overhead triceps extension (dumbbell)" },
  { category: "Triceps", name: "Overhead triceps extension (cable)" },
  { category: "Triceps", name: "Close grip bench press" },
  { category: "Triceps", name: "Dips (triceps)" },
  { category: "Triceps", name: "Kickbacks (dumbbell)" },
  { category: "Triceps", name: "Kickbacks (cable)" },
  { category: "Triceps", name: "Diamond push-ups" },

  { category: "Legs", name: "Squat" },
  { category: "Legs", name: "Squat (dumbbell)" },
  { category: "Legs", name: "Hack squat" },
  { category: "Legs", name: "Leg press" },
  { category: "Legs", name: "Lunges (barbell)" },
  { category: "Legs", name: "Lunges (dumbbell)" },
  { category: "Legs", name: "Bulgarian split squat" },
  { category: "Legs", name: "Leg extension (machine)" },
  { category: "Legs", name: "Leg curl (machine)" },
  { category: "Legs", name: "Leg curl (lying)" },
  { category: "Legs", name: "Stiff-leg deadlift" },
  { category: "Legs", name: "Hip thrust (barbell)" },
  { category: "Legs", name: "Hip thrust (machine)" },
  { category: "Legs", name: "Sumo squat" },
  { category: "Legs", name: "Step-ups" },
  { category: "Legs", name: "Goblet squat" },
  { category: "Legs", name: "Front squat" },

  { category: "Calves", name: "Standing calf raise (machine)" },
  { category: "Calves", name: "Seated calf raise (machine)" },
  { category: "Calves", name: "Calf raise (dumbbell)" },
  { category: "Calves", name: "Calf raise (smith machine)" },
  { category: "Calves", name: "Leg press calf raise" },

  { category: "Abs", name: "Crunches" },
  { category: "Abs", name: "Sit-ups" },
  { category: "Abs", name: "Plank" },
  { category: "Abs", name: "Leg raises" },
  { category: "Abs", name: "Hanging leg raises" },
  { category: "Abs", name: "Cable crunch" },
  { category: "Abs", name: "Russian twists" },
  { category: "Abs", name: "Ab wheel rollout" },
  { category: "Abs", name: "Mountain climbers" },
  { category: "Abs", name: "Bicycle crunches" },
  { category: "Abs", name: "Side plank" },

  { category: "Cardio", name: "Running" },
  { category: "Cardio", name: "Treadmill" },
  { category: "Cardio", name: "Rowing machine" },
  { category: "Cardio", name: "Cycling (outdoor)" },
  { category: "Cardio", name: "Stationary bike" },
  { category: "Cardio", name: "Elliptical" },
  { category: "Cardio", name: "Jump rope" },
  { category: "Cardio", name: "Stairmaster" },
  { category: "Cardio", name: "HIIT" },
  { category: "Cardio", name: "Swimming" },

  { category: "Olympic", name: "Clean and press" },
  { category: "Olympic", name: "Clean and jerk" },
  { category: "Olympic", name: "Snatch" },
  { category: "Olympic", name: "Power clean" },
  { category: "Olympic", name: "Push press" },
  { category: "Olympic", name: "Kettlebell swing" },
  { category: "Olympic", name: "Kettlebell clean" },
  { category: "Olympic", name: "Turkish get-up" },
];
